- repo: https://github.com/prettier/prettier
  rev: 1.17.1
  hooks:
    - id: prettier
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-json
